on:
  push:
    branches:
      - main
    tags:
      - 'v-*'

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi"

  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "there"
